### ISSUE TITLE
Change jotstick sensitivity [or something like that]

### ISSUE THREAD

**Issue by SeaborneProto** [gm666q/lswtcs-vita#13]
On joysticks with *slightest* drift [not actually present in anything else, it's the smallest offset], movement doesnt work properly [I.E, you will not run at full speed when joystick is at bottom right or bottom left, but will at top right/top left.

**Comment by SeaborneProto** [comment]
Pardon, I was an idiot.


Joystick cap was restricting my movement.

**Comment by Haasman0** [comment]
> Pardon, I was an idiot.
> 
> Joystick cap was restricting my movement.

This is the same for me, I just wish the controls were more sensitive because I like playing with the Joystick caps.
