### ISSUE TITLE
Some textures don't load in Through The Jundland Wastes

### ISSUE THREAD

**Issue by togguleru** [gm666q/lswtcs-vita#3]
![2024-09-26-011401](https://github.com/user-attachments/assets/70d67605-bb92-4dad-833b-23e320c7c983)

**Comment by gm666q** [comment]
Do you have a glsl folder in `ux0:data/lswtcs`? If so could you DM the content to me on Discord.

**Comment by togguleru** [comment]
sure, what's your discord?

**Comment by gm666q** [comment]
Do you have a glsl folder in `ux0:data/lswtcs`? If so could you DM the content to me on Discord.
