### ISSUE TITLE
Amazon Version 2.0.2.02 not supported

### ISSUE THREAD

**Issue by andiweli** [gm666q/lswtcs-vita#4]
As the title says.
Are there different version 2.0.2.02 ?

**Comment by gm666q** [comment]
Is this a questing? I haven't tested the Amazon version as I only have access to the Play Store version. If you have access to it and it's not working could you provide more details?

**Comment by andiweli** [comment]
Sure, what exact information do you need?

**Comment by gm666q** [comment]
Is there any error message, does it crash? In general what happens when you try to run it.

**Comment by andiweli** [comment]
That it's an "unsupported version". 
I can share the 2.0.2.02 version of Amazon if needed with you.

**Comment by gm666q** [comment]
Ok, I see. Could you DM me on Discord?
